version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: weekly
      day: "saturday"
      time: "01:00"
      timezone: "America/Los_Angeles"
    allow:
      - dependency-type: direct
